import Head from "next/head";
import PostList from "../../components/PostList";

export default function Photos({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList posts={posts} />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=10"
  );

  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
};
