import Head from "next/head";
import PhotoList from "../../components/PhotoList";

export default function Photos({ photos }) {
  console.log(photos);
  return (
    <div>
      <Head>
        <title>Photos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PhotoList photos={photos} />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/photos");

  const photos = await res.json();

  return {
    props: {
      photos,
    },
  };
};
